<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-C4T3QLF" failures="1" tests="9" name="runner.TestRunner" time="5.168" errors="0" timestamp="2023-09-21T17:25:31 EDT" skipped="0">
  <testcase classname="runner.TestRunner" name="runScenario" time="0.110"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.135"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.465"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.244"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.141"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.108"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="3.686">
    <failure message="expected [https://dsportalapp.herokuapp.com/home] but found [https://dsportalapp.herokuapp.com/register]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://dsportalapp.herokuapp.com/home] but found [https://dsportalapp.herokuapp.com/register]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at utilities.UtlityFunctions.check_url(UtlityFunctions.java:25)
at utilities.UtlityFunctions.check_url_home(UtlityFunctions.java:46)
at step_definition.Register_SD.user_willl_direct_to_home_page(Register_SD.java:39)
at âœ½.user willl direct to home page(file:///C:/Users/bobby/eclipse-workspace/ds-algo-quality-way/src/test/resources/features/Register.feature:76)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.TestRunner" name="runScenario" time="0.085"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.194"/>
</testsuite> <!-- runner.TestRunner -->
